version: "3"
services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile-frontend
    volumes:
      - ./app:/usr/src/app/
    ports:
      - 8081:8081
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile-backend
    volumes:
      - ./app:/usr/src/app/
    ports:
      - 4000:4000
